### ISSUE TITLE
Registration flow completed functionality

### ISSUE THREAD

**Issue by ezrichards** [ColoradoSchoolOfMines/mineshspc.com#24]
In the registration flow checklist, add style "completed" to the span register-item if the user has completed that task; this may require extra backend functionality.

**Comment by sumnerevans** [comment]
How would this work? Students and parents won't fill out the forms at the same time, so progress will be more or less meaningless.

**Comment by ezrichards** [comment]
I was thinking it may be useful for teachers to see a checklist of things they still need to do (and if they still need to encourage students and parents to fill out their forms). It would probably be a bit more work on the backend to hook that up though, so I understand if we don't need that functionality.

Let me know if we don't need it and I can go in and remove the completed styling.

**Comment by sumnerevans** [comment]
It doesn't make a ton of sense because we would have to represent each team somehow, and each person on each team, and also only conditionally color it if they're logged in. Besides, I already have progress displays when you are logged in and go to `/register/teacher/teams`.

BTW, you should be able to test out the flow at this point by creating an account on mineshspc.com. I'm going to blow everything away before we open to the public, so it's basically a testing environment at this point.
