### ISSUE TITLE
Make footer responsive

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/mineshspc.com#31]

**Comment by ezrichards** [comment]
Looks like the archive page spacing is a little unresponsive too.

**Comment by ezrichards** [comment]
Footer fixed via a901c1, archive fixed via 439f7f

The footer wasn't scaling properly because of the `height` tag, but removing it seems to do the job and still keep a coherent footer on both web & mobile. If it doesn't look good, try adding more vertical padding/margin.

The archive is still a bit too vertically spaced, but it's better. It may just be the nature of our content, and I don't know if it's really worth it to write mobile-specific styling.
